//////////////////////////////////////////////////////////////////////////////////////////////
// DO NOT MODIFY THIS FILE                                                                  //
// This file is automatically generated by ZenStack CLI and should not be manually updated. //
//////////////////////////////////////////////////////////////////////////////////////////////

/* eslint-disable */

import { type SchemaType as $Schema } from "./schema";
import type { FindManyArgs as $FindManyArgs, FindUniqueArgs as $FindUniqueArgs, FindFirstArgs as $FindFirstArgs, CreateArgs as $CreateArgs, CreateManyArgs as $CreateManyArgs, CreateManyAndReturnArgs as $CreateManyAndReturnArgs, UpdateArgs as $UpdateArgs, UpdateManyArgs as $UpdateManyArgs, UpdateManyAndReturnArgs as $UpdateManyAndReturnArgs, UpsertArgs as $UpsertArgs, DeleteArgs as $DeleteArgs, DeleteManyArgs as $DeleteManyArgs, CountArgs as $CountArgs, AggregateArgs as $AggregateArgs, GroupByArgs as $GroupByArgs, WhereInput as $WhereInput, SelectInput as $SelectInput, IncludeInput as $IncludeInput, OmitInput as $OmitInput, QueryOptions as $QueryOptions } from "@zenstackhq/orm";
import type { SimplifiedPlainResult as $Result, SelectIncludeOmit as $SelectIncludeOmit } from "@zenstackhq/orm";
export type ClinicFindManyArgs = $FindManyArgs<$Schema, "Clinic">;
export type ClinicFindUniqueArgs = $FindUniqueArgs<$Schema, "Clinic">;
export type ClinicFindFirstArgs = $FindFirstArgs<$Schema, "Clinic">;
export type ClinicCreateArgs = $CreateArgs<$Schema, "Clinic">;
export type ClinicCreateManyArgs = $CreateManyArgs<$Schema, "Clinic">;
export type ClinicCreateManyAndReturnArgs = $CreateManyAndReturnArgs<$Schema, "Clinic">;
export type ClinicUpdateArgs = $UpdateArgs<$Schema, "Clinic">;
export type ClinicUpdateManyArgs = $UpdateManyArgs<$Schema, "Clinic">;
export type ClinicUpdateManyAndReturnArgs = $UpdateManyAndReturnArgs<$Schema, "Clinic">;
export type ClinicUpsertArgs = $UpsertArgs<$Schema, "Clinic">;
export type ClinicDeleteArgs = $DeleteArgs<$Schema, "Clinic">;
export type ClinicDeleteManyArgs = $DeleteManyArgs<$Schema, "Clinic">;
export type ClinicCountArgs = $CountArgs<$Schema, "Clinic">;
export type ClinicAggregateArgs = $AggregateArgs<$Schema, "Clinic">;
export type ClinicGroupByArgs = $GroupByArgs<$Schema, "Clinic">;
export type ClinicWhereInput = $WhereInput<$Schema, "Clinic">;
export type ClinicSelect = $SelectInput<$Schema, "Clinic">;
export type ClinicInclude = $IncludeInput<$Schema, "Clinic">;
export type ClinicOmit = $OmitInput<$Schema, "Clinic">;
export type ClinicGetPayload<Args extends $SelectIncludeOmit<$Schema, "Clinic", true>, Options extends $QueryOptions<$Schema> = $QueryOptions<$Schema>> = $Result<$Schema, "Clinic", Args, Options>;
export type TreatmentFindManyArgs = $FindManyArgs<$Schema, "Treatment">;
export type TreatmentFindUniqueArgs = $FindUniqueArgs<$Schema, "Treatment">;
export type TreatmentFindFirstArgs = $FindFirstArgs<$Schema, "Treatment">;
export type TreatmentCreateArgs = $CreateArgs<$Schema, "Treatment">;
export type TreatmentCreateManyArgs = $CreateManyArgs<$Schema, "Treatment">;
export type TreatmentCreateManyAndReturnArgs = $CreateManyAndReturnArgs<$Schema, "Treatment">;
export type TreatmentUpdateArgs = $UpdateArgs<$Schema, "Treatment">;
export type TreatmentUpdateManyArgs = $UpdateManyArgs<$Schema, "Treatment">;
export type TreatmentUpdateManyAndReturnArgs = $UpdateManyAndReturnArgs<$Schema, "Treatment">;
export type TreatmentUpsertArgs = $UpsertArgs<$Schema, "Treatment">;
export type TreatmentDeleteArgs = $DeleteArgs<$Schema, "Treatment">;
export type TreatmentDeleteManyArgs = $DeleteManyArgs<$Schema, "Treatment">;
export type TreatmentCountArgs = $CountArgs<$Schema, "Treatment">;
export type TreatmentAggregateArgs = $AggregateArgs<$Schema, "Treatment">;
export type TreatmentGroupByArgs = $GroupByArgs<$Schema, "Treatment">;
export type TreatmentWhereInput = $WhereInput<$Schema, "Treatment">;
export type TreatmentSelect = $SelectInput<$Schema, "Treatment">;
export type TreatmentInclude = $IncludeInput<$Schema, "Treatment">;
export type TreatmentOmit = $OmitInput<$Schema, "Treatment">;
export type TreatmentGetPayload<Args extends $SelectIncludeOmit<$Schema, "Treatment", true>, Options extends $QueryOptions<$Schema> = $QueryOptions<$Schema>> = $Result<$Schema, "Treatment", Args, Options>;
export type TreatmentsByClinicFindManyArgs = $FindManyArgs<$Schema, "TreatmentsByClinic">;
export type TreatmentsByClinicFindUniqueArgs = $FindUniqueArgs<$Schema, "TreatmentsByClinic">;
export type TreatmentsByClinicFindFirstArgs = $FindFirstArgs<$Schema, "TreatmentsByClinic">;
export type TreatmentsByClinicCreateArgs = $CreateArgs<$Schema, "TreatmentsByClinic">;
export type TreatmentsByClinicCreateManyArgs = $CreateManyArgs<$Schema, "TreatmentsByClinic">;
export type TreatmentsByClinicCreateManyAndReturnArgs = $CreateManyAndReturnArgs<$Schema, "TreatmentsByClinic">;
export type TreatmentsByClinicUpdateArgs = $UpdateArgs<$Schema, "TreatmentsByClinic">;
export type TreatmentsByClinicUpdateManyArgs = $UpdateManyArgs<$Schema, "TreatmentsByClinic">;
export type TreatmentsByClinicUpdateManyAndReturnArgs = $UpdateManyAndReturnArgs<$Schema, "TreatmentsByClinic">;
export type TreatmentsByClinicUpsertArgs = $UpsertArgs<$Schema, "TreatmentsByClinic">;
export type TreatmentsByClinicDeleteArgs = $DeleteArgs<$Schema, "TreatmentsByClinic">;
export type TreatmentsByClinicDeleteManyArgs = $DeleteManyArgs<$Schema, "TreatmentsByClinic">;
export type TreatmentsByClinicCountArgs = $CountArgs<$Schema, "TreatmentsByClinic">;
export type TreatmentsByClinicAggregateArgs = $AggregateArgs<$Schema, "TreatmentsByClinic">;
export type TreatmentsByClinicGroupByArgs = $GroupByArgs<$Schema, "TreatmentsByClinic">;
export type TreatmentsByClinicWhereInput = $WhereInput<$Schema, "TreatmentsByClinic">;
export type TreatmentsByClinicSelect = $SelectInput<$Schema, "TreatmentsByClinic">;
export type TreatmentsByClinicInclude = $IncludeInput<$Schema, "TreatmentsByClinic">;
export type TreatmentsByClinicOmit = $OmitInput<$Schema, "TreatmentsByClinic">;
export type TreatmentsByClinicGetPayload<Args extends $SelectIncludeOmit<$Schema, "TreatmentsByClinic", true>, Options extends $QueryOptions<$Schema> = $QueryOptions<$Schema>> = $Result<$Schema, "TreatmentsByClinic", Args, Options>;
