//////////////////////////////////////////////////////////////////////////////////////////////
// DO NOT MODIFY THIS FILE                                                                  //
// This file is automatically generated by ZenStack CLI and should not be manually updated. //
//////////////////////////////////////////////////////////////////////////////////////////////

/* eslint-disable */

import { type SchemaType as $Schema } from "./schema";
import { type ModelResult as $ModelResult, type TypeDefResult as $TypeDefResult } from "@zenstackhq/orm";
export type Clinic = $ModelResult<$Schema, "Clinic">;
export type TreatmentsByClinic = $ModelResult<$Schema, "TreatmentsByClinic">;
export type Treatment = $ModelResult<$Schema, "Treatment">;
export type Auth = $TypeDefResult<$Schema, "Auth">;
